### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by FanManutd** [Olga-smart/FSD_2#20]
1. Почему решила инициализировать классы через `init` метод, а не конструктор? Ты же всё равно в итоге в `init` вызываешь `new Component()`. Обычно основной способ инициализировать класс - это как раз таки вызов конструктора. В других способах здесь нет нужды. 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/f114f1c2-3c98-49d1-bda2-d63ba250fb9c)

2. Надо переосмыслить архитектуру. Давай рассмотрим на примере класса `Input`.  
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/bb724789-5f5a-4946-97f3-ba70a951f13d)
Ты инициализируешь класс для каждого компонента input на странице, но экземпляры этого класса нигде не сохраняются. Это приводит к целой цепочке проблем. Например, что бы взаимодействовать с классом `Input`, тебе надо найти нужный инпут в html и передать его в качестве аргумента метода: 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/00e6e17d-4283-4b41-b88f-43af13f8c151)
что в свою очередь заставляет классу Dropdown знать о том, как устроен компонент `input` внутри себя. Он знает о внутреннем css-классе `input` компонента `input`, но он не должен об этом знать. 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/1ed118df-cccd-4b51-a91e-72f3e79d2571)
Более того, метод handleDropdownToggleв принципе никак не связан с классом `Input` и может получить любой html элемент и сделать на нём `classList.toggle`, но результата никакого не будет, ведь этот метод нужен только для взаимодействия с компонентом `input`. Только компонент может знать, какие классы ему надо поменять, что бы изменить внешний вид.
Было бы правильней, если бы `Input` вызывал `classList.toggle` на собственном экземпляре, то есть на `this._component`. А для этого необходимо, что бы экземпляр класса создавался там, где он используется. То есть если `Dropdown` использует `Input`, то он создаёт экземпляр класса (передавая родительский html элемент, к которому подключается `input`) и хранит его у себя, для дальнейшего взаимодействия с ним. И так можно сделать со всеми js-классами. Создавать экземпляр только там, где подключается компонент, будь то страница или другой компонент. Так же такая инициализация позволит передавать какие-то свойства/параметры в js-класс. Например можно передать настройки дропдауна. Тут в целом не критично, можно и через data-атрибуты передавать, как ты это сейчас делаешь, но через параметры будет гораздо наглядней.

3. Есть и другие проблемы. Например зачем здесь в html-элементе создавать, хранить, а потом использовать какие-то новые свойства?  У тебя же есть js-класс для этого, незачем редактировать html-структуру)
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/14d4ab75-8863-4ae9-8b1b-d0451d6bc861)

4. Проблема с неймингом, а именно в том, что класс `Input` почему-то знает, что где-то есть какой-то `Dropdown` и состояние этого Dropdown-а влияет на css-классы Input. Хотя сам по себе компонент `input` никак не взаимодействует с `dropdown`. Это неверно. Надо рассматривать компонент как самостоятельную и независимую сущность. Да, компоненты могут вкладываться друг в друга, но взаимодействовать между собой они должны через прозрачный и не привязанный к чему-либо API. А точнее API компонента должно быть связано только с самим компонентом. 
Короче говоря, если инпут должен предоставлять API для изменения своего внешнего вида, то метод для этого так и должен называться и не иметь словесной привязки к другим компонентам. Соответственно, сам метод и модификатор `dropdown_open` должны называться иначе. 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/29416aee-27db-4f0b-b14a-ef4e046d576f)

5. Это явно не должно быть статическим методом. Я предлагаю отключить правило eslint, связанное с требованием использовать `this` в методах класса. И убрать везде static, если этот метод не подразумевает своё использование без создания экземпляра. 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/1687a3d7-d56a-4769-991c-a84139da87f4)

**Comment by Olga-smart** [comment]
> 1. Почему решила инициализировать классы через `init` метод, а не конструктор?

Решила так сделать, потому что иначе ESLint ругался:
![image](https://github.com/Olga-smart/FSD_2/assets/33065109/2f6da575-d10d-4b97-9f9f-a1ba7b92a37a)
Но теперь я обнаружила, что если написать стрелочную функцию в 1 строку, ESLint ругаться не будет:
![image](https://github.com/Olga-smart/FSD_2/assets/33065109/cdb1c6b9-02e7-4184-b088-70f78476b44b)
Так и сделала. 
Иными словами, нужен был return перед вызовом конструктора.

**Comment by Olga-smart** [comment]
**`Input:`**

1. Теперь js-класс `Input` можно инициализировать при необходимости. По умолчанию он не инициализируется, т. к. в большинстве случаев нам не нужно взаимодействовать с этим компонентом с помощью js. 

2. Класс `Input` инициализируется на обертке, а не на самом теге `input`. Сделала это на случай, если в будущем захотим делать что-нибудь еще с тегом `label`, например. Да и вообще чтобы не трогать снаружи внутренности компонента `input`.

3. Заменила класс `input__field_dropdown_open` на `input__field_bottom_flat`. Изначально, я не задумывала это как привязку к компоненту `dropdown`, а имела ввиду, что у инпута может быть какой-нибудь дропдаун (например: счетчик, календарь, выбор из списка и т. п.) и при открытии такого дропдауна инпут должен менять свой внешний вид. Но потом поняла, что не всегда инпут должен принимать именно такой вид. К примеру, в нашем случае с календарем, у инпута углы остаются скругленными.

**Comment by Olga-smart** [comment]
> 4. Проблема с неймингом, а именно в том, что класс `Input` почему-то знает, что где-то есть какой-то `Dropdown` 

Ой, не подозревала, что редактирую html-структуру 🙈 Исправила это, но меня смущает тот факт, что теперь гораздо чаще происходит поиск по DOM-дереву. Скорее всего это нехорошо, но не соображу как лучше это оптимизировать 🤔

**Comment by Olga-smart** [comment]
> И так можно сделать со всеми js-классами. Создавать экземпляр только там, где подключается компонент, будь то страница или другой компонент.

Я прошлась по всем компонентам чтобы понять, нет ли у меня проблем, похожих на то, что было с `dropdown` и `input`. Во всех остальных случаях у меня js-классы инициализируются только ради обработчиков событий, т. е. другие компоненты с ними с помощью js не взаимодействуют. Кроме одного - класс `CardBooking` находит в DOM тег `input` компонента `input`, берет из него` value` и навешивает на этот тег свои обработчики событий. 
❓Насколько это критично? Лучше добавить в js-класс `Input` методы `getValue()` и `addEventListener()` и обращаться к компоненту через них или оставить как есть?

**Comment by FanManutd** [comment]
> Исправила это, но меня смущает тот факт, что теперь гораздо чаще происходит поиск по DOM-дереву.

А почему чаще? Можешь объяснить?

> Насколько это критично? 

Это критично настолько же, насколько и предыдущий случай) `CardBooking` знает о внутренностях компонента `input`. Если тебе нужно реагировать на ввод инпута, то лучше тебе прокинуть в `Input` функцию-коллбэк, которую `Input` сам назначит обработчиком события.

**Comment by Olga-smart** [comment]
> А почему чаще? Можешь объяснить?

Прошу прощения, я по ошибке процитировала не тот отрывок. Мой комментарий относится к тексту: _"зачем здесь в html-элементе создавать, хранить, а потом использовать какие-то новые свойства?"_

На всякий случай все же поясню: 

Раньше при вызове конструктора кнопки плюс, минус и инпут каждого item-a дропдауна записывались в его свойство и при последующих обращениях к ним происходило обращение к этому свойству:
![image](https://github.com/Olga-smart/FSD_2/assets/33065109/c80a889a-ca85-4805-99db-a684e38488b3)

А теперь всякий раз приходится использовать `querySelector` чтобы обратиться к нужному элементу. Это происходит в следующих методах: `setGuestsProperties()`, `setFacilitiesProperties()`, `sumValues()`, `counterValueIsMinimal(item)`, `counterValueIsMaximal(item)`, `buttonResetIsNecessary()`, `reset()`

Нагляднее можно посмотреть в [коммите](https://github.com/Olga-smart/FSD_2/commit/723041fa82026a0df3fcaf8623ad5650fc950c8a): строки 25, 39, 63, 66, 71, 74 и т. д. (там дальше аналогично).

**Comment by FanManutd** [comment]
> А теперь всякий раз приходится использовать `querySelector` чтобы обратиться к нужному элементу. 

Так сохрани их куда-нибудь при инициализации, просто не в html-структуре.  Например из `this._items` можно сделать массив объектов. Моё замечание было в том, что незачем редактировать html-структуру, когда у тебя есть целый класс, в котором ты можешь хранить все нужные данные.

**Comment by Olga-smart** [comment]
> Так сохрани их куда-нибудь при инициализации, просто не в html-структуре. Например из `this._items` можно сделать массив объектов.

Так и [сделала](https://github.com/Olga-smart/FSD_2/commit/55d35b895a262d2d429d64dc84c042a954c01cd7). Правда все же не везде удалось избавиться от поиска по DOM-дереву. `querySelector` остался в методах: `_counterValueIsMinimal`, `_counterValueIsMaximal`, `_handleMinusClick`, `_handlePlusClick`.

**Comment by FanManutd** [comment]
> Правда все же не везде удалось избавиться от поиска по DOM-дереву. querySelector остался в методах: _counterValueIsMinimal, _counterValueIsMaximal, _handleMinusClick, _handlePlusClick.

В двух первых методах тебе не нужно искать инпут, он у тебя и так уже есть, просто передай его) 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/4dfe0b8c-2160-46ba-9a03-bb4a8c117c67)

В остальных двух методах ты вместе с привязкой `this` можешь привязать любые данные и получить их в своих обработчиках. Воспользуйся этим и тебе не придётся искать `item` и всё остальное.
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/874d496e-6905-419f-95e7-9b69018c865b)

6. По максимуму избавляемся от `let` переменных. Здесь можно избавиться от `let`,  а `value+/-=1` можно положить в `const newValue`.
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/8fe39fee-0061-44fd-8e38-4f1839abca34)
Здесь нет необходимости в перезаписи. Лучше явно разделить на `arrivalDate` и `departureDate` и т.д. 
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/dab88b17-02f3-47ca-aede-df3dca621736)
Здесь применить `reduce` метод
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/5c7d44f9-ce9e-4d28-8adb-d1c66acc7357)
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/7fd4ec3d-c07e-4949-bafd-c31720a7c514)
Здесь использовать const, а в `if` ветках сразу делать `return`.
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/73b8a46a-e05f-46ae-a40b-32d1fdee8e5d)
Здесь так же добавляем const переменные.
![image](https://github.com/Olga-smart/FSD_2/assets/90761929/c6f3df76-5668-4199-9465-0a84af061bfa)
